version = 1

[compositor]
backend = "hyprland"
primary_output = ""

[users]
mode = "list"
min_uid = 1000
max_uid = 59999
include = []
exclude = ["greeter", "nobody"]
show_avatars = true

[sessions]
directories = ["/usr/local/share/wayland-sessions", "/usr/share/wayland-sessions"]
include = []
exclude = []
default = "holonight-hyprland.desktop"

[keyboard]
default = "us"
options = ""
layouts = [
  { id = "us", layout = "us", variant = "", label = "EN" },
  { id = "ua", layout = "ua", variant = "", label = "UA" }
]

[appearance]
background = "/usr/share/holonight-greeter/backgrounds/wallpaper.png"
