#include "sessionlauncher.h"

#include <algorithm>

namespace {
QString luaString(QString value) {
  value.replace('\\', "\\\\");
  value.replace('"', "\\\"");
  value.replace('\n', "\\n");
  value.replace('\r', "\\r");
  return '"' + value + '"';
}
}  // namespace

namespace Greeter {
BackendCommand cageCommand(const QString& greeter, const QString& config) {
  return {
      .program = "dbus-run-session",
      .arguments = {"cage", "-s", "-m", "extend", "-d", "--", greeter, "--config", config},
  };
}

BackendCommand hyprlandCommand(const QString& config) {
  return {.program = "dbus-run-session", .arguments = {"start-hyprland", "--", "--config", config}};
}

QString hyprlandConfig(const Config& config, const QString& greeter, const QString& configPath) {
  QStringList layouts;
  QStringList variants;
  QList<KeyboardLayout> ordered = config.keyboard_layouts;
  const auto configured = std::ranges::find(ordered, config.keyboard_default, &KeyboardLayout::id);
  if (configured != ordered.end()) {
    std::ranges::rotate(ordered, configured);
  }
  for (const auto& entry : ordered) {
    layouts += entry.layout;
    variants += entry.variant;
  }
  if (layouts.isEmpty()) {
    layouts += "us";
  }
  QString result =
      "-- Generated by holonight-greeter-session; isolated from user config.\n"
      "hl.monitor({ output = \"\", mode = \"preferred\", position = \"auto\", "
      "scale = 1 })\n"
      "hl.config({\n"
      "  misc = { disable_hyprland_logo = true, "
      "disable_splash_rendering = true },\n"
      "  input = { kb_layout = " +
      luaString(layouts.join(',')) + ", kb_variant = " + luaString(variants.join(',')) +
      ", kb_options = " + luaString(config.keyboard_options) +
      " },\n"
      "})\n"
      "hl.on(\"hyprland.start\", function()\n"
      "  hl.exec_cmd(" +
      luaString(greeter + " --config " + configPath) +
      ")\n"
      "end)\n";
  return result;
}
}  // namespace Greeter
